line-length = 88
target-version = "py313"

[lint]
# pyproject.tomlと統一: 必須ルールのみ
select = ["E", "F", "W", "I", "UP", "B", "C4", "PIE", "PT", "RET", "SIM", "ARG", "PTH", "RUF"]

# より寛容な設定
ignore = [
    "B008",    # Do not perform function calls in argument defaults (typer pattern)
    "ARG001",  # Unused function argument (CLI placeholders)
    "RET504",  # Unnecessary assignment before return
    "SIM108",  # Use ternary operator (readability preference)
    "PTH123",  # Path.open() instead of open() (compatibility)
    "E501",    # Line too long (handled by formatter)
    "F841",    # Local variable assigned but never used
    "B017",    # pytest.raises(Exception) is acceptable
]

[lint.per-file-ignores]
"tests/**/*.py" = [
    "ARG001",  # Unused function argument (fixtures)
    "PTH",     # Path rules (test files can use string paths)
    "F841",    # Unused variables in tests
    "B017",    # pytest.raises(Exception) is acceptable
    "E501",    # Long lines in test data
]
"experiments/**/*.py" = [
    "T201",    # print() allowed in experiments
    "E501",    # Long lines allowed in experiments
    "F841",    # Unused variables allowed in experiments
]
