line-length = 88
target-version = "py313"

[lint]
select = ["E", "F", "W", "I", "N", "UP", "B", "A", "C4", "PIE", "PT", "Q", "RET", "SIM", "ARG", "PTH", "PL", "RUF"]

# Ignore specific rules that are too strict for our use case
ignore = [
    "B008",    # Do not perform function calls in argument defaults (typer pattern)
    "FBT001",  # Boolean typed positional argument
    "FBT003",  # Boolean positional value in function call
    "ARG001",  # Unused function argument (CLI placeholders)
    "PLR0913", # Too many arguments (CLI commands)
    "PLR6301", # Method could be static (pytest methods need self)
    "PLR2004", # Magic value used in comparison (test constants)
]

[lint.per-file-ignores]
"tests/**/*.py" = [
    "S101",    # Use of assert detected (pytest uses asserts)
]
