# Keyword Extraction Configuration
# キーワード抽出設定ファイル

metadata:
  version: "1.0.0"
  description: "Configuration for keyword extraction from markdown content"
  last_updated: "2025-01-25"
  contributors: ["knowledge-base-organizer"]

# 除外する一般的な単語（日本語・英語）
common_words:
  english:
    - "the"
    - "and"
    - "for"
    - "are"
    - "but"
    - "not"
    - "you"
    - "all"
    - "can"
    - "had"
    - "her"
    - "was"
    - "one"
    - "our"
    - "out"
    - "day"
    - "get"
    - "has"
    - "him"
    - "his"
    - "how"
    - "its"
    - "may"
    - "new"
    - "now"
    - "old"
    - "see"
    - "two"
    - "who"
    - "boy"
    - "did"
    - "she"
    - "use"
    - "way"
    - "will"
    - "with"
    - "have"
    - "this"
    - "that"
    - "from"
    - "they"
    - "know"
    - "want"
    - "been"
    - "good"
    - "much"
    - "some"
    - "time"
    - "very"
    - "when"
    - "come"
    - "here"
    - "just"
    - "like"
    - "long"
    - "make"
    - "many"
    - "over"
    - "such"
    - "take"
    - "than"
    - "them"
    - "well"
    - "were"
    - "what"
    - "your"
    - "about"
    - "after"
    - "again"
    - "before"
    - "could"
    - "first"
    - "found"
    - "great"
    - "other"
    - "right"
    - "should"
    - "these"
    - "think"
    - "where"
    - "would"
    - "write"
    - "also"
    - "cover"
    - "document"
    - "discusses"
    - "includes"
    - "text"
    - "content"

  japanese:
    - "これ"
    - "それ"
    - "あれ"
    - "この"
    - "その"
    - "あの"
    - "ここ"
    - "そこ"
    - "あそこ"
    - "です"
    - "である"
    - "だった"
    - "でした"
    - "します"
    - "しました"
    - "という"
    - "として"
    - "について"
    - "による"
    - "によって"
    - "において"
    - "に関して"
    - "に対して"
    - "のため"
    - "ので"
    - "から"
    - "まで"
    - "など"
    - "なお"
    - "また"
    - "さらに"
    - "ただし"
    - "しかし"
    - "けれど"
    - "でも"
    - "そして"
    - "または"
    - "もしくは"
    - "および"
    - "ならびに"

# 重要なキーワードパターン（優先的に抽出）
important_keywords:
  # 技術用語パターン
  technical_terms:
    patterns:
      - "\\b[A-Z]{2,}\\b"  # 大文字の略語 (API, HTTP, etc.)
      - "\\b[A-Z][a-z]+[A-Z][a-zA-Z]*\\b"  # CamelCase (JavaScript, etc.)
      - "\\b[a-z]+_[a-z]+\\b"  # snake_case
      - "\\b[a-z]+-[a-z]+\\b"  # kebab-case

    # 特定の技術用語
    specific_terms:
      - "API"
      - "REST"
      - "GraphQL"
      - "JSON"
      - "XML"
      - "HTTP"
      - "HTTPS"
      - "SSL"
      - "TLS"
      - "OAuth"
      - "JWT"
      - "SQL"
      - "NoSQL"
      - "MongoDB"
      - "PostgreSQL"
      - "MySQL"
      - "Redis"
      - "Docker"
      - "Kubernetes"
      - "AWS"
      - "Azure"
      - "GCP"
      - "CI/CD"
      - "DevOps"
      - "Git"
      - "GitHub"
      - "GitLab"
      - "JavaScript"
      - "TypeScript"
      - "Python"
      - "Java"
      - "C++"
      - "React"
      - "Vue"
      - "Angular"
      - "Node.js"
      - "Express"
      - "Django"
      - "Flask"
      - "Spring"
      - "Laravel"

  # 日本語の重要キーワード
  japanese_terms:
    # プログラミング関連
    programming:
      - "プログラミング"
      - "アルゴリズム"
      - "データ構造"
      - "オブジェクト指向"
      - "関数型プログラミング"
      - "デザインパターン"
      - "リファクタリング"
      - "テスト駆動開発"
      - "アジャイル開発"
      - "スクラム"
      - "カンバン"

    # システム設計
    system_design:
      - "システム設計"
      - "アーキテクチャ"
      - "マイクロサービス"
      - "モノリス"
      - "スケーラビリティ"
      - "可用性"
      - "パフォーマンス"
      - "セキュリティ"
      - "負荷分散"
      - "キャッシュ"
      - "データベース設計"

    # 機械学習・AI
    machine_learning:
      - "機械学習"
      - "深層学習"
      - "ニューラルネットワーク"
      - "自然言語処理"
      - "コンピュータビジョン"
      - "強化学習"
      - "教師あり学習"
      - "教師なし学習"
      - "特徴量エンジニアリング"
      - "モデル評価"
      - "過学習"
      - "汎化性能"

    # ビジネス・経営
    business:
      - "ビジネスモデル"
      - "戦略"
      - "マーケティング"
      - "ブランディング"
      - "顧客体験"
      - "ユーザーエクスペリエンス"
      - "プロダクトマネジメント"
      - "プロジェクトマネジメント"
      - "リーダーシップ"
      - "チームビルディング"

# キーワード抽出設定
extraction_settings:
  # 最小キーワード長
  min_keyword_length: 3

  # 最大キーワード長
  max_keyword_length: 50

  # 数字のみのキーワードを除外するか
  exclude_numbers_only: true

  # 特殊文字を含むキーワードを除外するか
  exclude_special_chars: true

  # 大文字小文字を区別するか
  case_sensitive: false

  # 重複キーワードを除去するか
  remove_duplicates: true

  # 最大抽出キーワード数（0は無制限）
  max_keywords: 100

# カテゴリ別重み設定
category_weights:
  technical_terms: 1.5
  japanese_terms: 1.2
  proper_nouns: 1.3
  compound_words: 1.1
  default: 1.0

# ユーザー定義キーワード
user_defined_keywords:
  # ユーザーが独自に追加するキーワード
  # 例:
  # custom_important:
  #   - "マイキーワード"
  #   - "重要な用語"
  #
  # custom_exclude:
  #   - "除外したい単語"
